apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-demo
  labels:
    app: java-demo
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 20
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        resources:
          limits:
            cpu: 400m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 512Mi
