{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: java-demo
  labels:
    app: java-demo
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: java-demo
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
