apiVersion: v1
kind: Service
metadata:
  name: java-demo
  labels:
    app: java-demo
  annotations:
    prometheus.io/path: "/prometheus"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: java-demo
