apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    flux.weave.works/automated: "true"
  creationTimestamp: null
  generation: 1
  labels:
    app: java-demo
  name: java-demo
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/java-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: java-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-demo
    spec:
      containers:
      - image: gcr.io/dx-general/java-demo:e723ad776b0274cddda68501b48b9aab3f2df545
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
